# Generated by Django 5.2.17 on 2026-09-13 08:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('role', models.CharField(choices=[('frontend', 'Frontend Developer'), ('backend', 'Backend Developer'), ('fullstack', 'Full-Stack Developer'), ('mobile', 'Mobile Developer'), ('designer', 'UI/UX Designer'), ('data', 'Data Engineer/Analyst'), ('other', 'Other')], default='fullstack', max_length=20)),
                ('tech_stack', models.CharField(blank=True, help_text="Comma-separated, e.g. 'React, Django, PostgreSQL'", max_length=255)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('project_url', models.URLField(blank=True, null=True)),
                ('repo_url', models.URLField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
