# Generated by Django 5.2.17 on 2026-09-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='started_at',
            field=models.DateTimeField(),
        ),
    ]
